services:
  api:
    build:
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      # uncommenting this changes 'localhost' for the given hostname on url responses
      # - API_URL="http://192.168.0.11"
    develop:
      watch:
        - path: "."
          action: rebuild