services:
  api:
    image: "neozmmv/tungsten:latest"
    ports:
      - "9007:9007"
    environment:
      - PORT=9007
      # uncommenting this changes 'localhost' for the given hostname on url responses
      # - API_URL=http://192.168.0.11:9007 # WITHOUT QUOTES! (")
    restart: unless-stopped